routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/slides/{slide}/updateorder','SlideController@updateOrder')->name('slides.updateorder');


Route::resource('projects','ProjectController');
Route::resource('projects.slides','SlideController')->shallow();
Route::resource('slides.animation','AnimationController');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = ['name'];

    public function users(){
        return $this->belongsToMany('App\User','user_project');
    }

    public function slides(){
        return $this->hasMany('App\Slide');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //Get all user projects
        $projects = \Auth::user()->projects;
        // Return the view with the projects
        return view('projects.index',['projects'=>$projects]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // Load project creation form
        return view('projects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //First validate the values
        $validatedData = $request->validate([
           'projectName' => 'required',
        ]);

        //Create project
        $project = new Project;
        $project->name = $validatedData['projectName'];
        $project->save();

        \Auth::user()->projects()->attach($project);

        return \redirect('projects');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $project = Project::find($id);
        $slides = $project->slides()->orderBy('order','asc')->get();

        return view('projects.show',[
            'project' => $project,
            'slides_orm' => $slides,
            'slides' => $slides->toJson()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //Get the corresponding project
        $project = auth()->user()->projects->find($id);
        //Send 403 if the user is not the creator of this project
        if($project == null){
            abort(403);
        }

        return view('projects.edit',[
            'project'=>$project,
            'slides'=>$project->slides->sortBy('order')
        ]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $project = Project::find($id);
        $slides = $project->slides();
        $slides->delete();
        $project->delete();

        return \redirect(route('projects.index'));
    }
}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1 class="text-center">Create your new project</h1>

        <form method="POST" action="{{ url('projects') }}">
            @csrf
            <div class="form-group">
                <label for="projectName">Project name</label>
                <input type="text" name="projectName" id="projectName" aria-describedby="projectNameHelp" class="form-control @error('projectName') is-invalid @enderror">
                <small id="projectNameHelp" class="form-text text-muted">Choose a good name</small>
                @error('projectName')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
                @enderror
            </div>

            <button type="submit" class="btn btn-primary">Create</button>
            <a href="{{url()->previous()}}" class="btn btn-danger">Cancel</a>
        </form>
    </div>

@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center mb-5">
        <h1 class="m-0 mr-3">{{ $project->name }}</h1>
        <form method="POST" action="{{route('projects.destroy',$project)}}">
            @csrf
            @method('DELETE')
            <button type="submit" class="btn btn-outline-danger">Delete</button>
        </form>
    </div>

    <div class="row justify-content-center mb-5">
        <a href="{{route('projects.show',$project)}}" class="btn btn-outline-primary">Go to preview</a>
    </div>

    <div class="row justify-content-center mb-5">
        <h1 class="m-0 mr-3">Slides</h1> <a href="{{route('projects.slides.create',$project)}}" class="btn btn-outline-primary">+</a>
    </div>
    <div class="justify-content-center d-flex pl-5" style="overflow-x: scroll;">
        @if($slides->isEmpty())
            <h4 class="text-center">Create your first slide with the + button !</h4>
        @endif
        @foreach($slides as $slide)
            <div class="card mr-1" style="width: 18rem; min-width: 18rem">
                <img class="card-img-top" src="{{url($slide->image->url)}}">
                <div class="card-body">
                    <a href="{{url('slides/'.$slide->id.'/edit')}}" class="btn btn-primary">Edit</a>
                    <a href="{{route('slides.updateorder',[$slide,'action'=>'next'])}}"
                       class="btn btn-light float-right {{$slide->order == count($slides)-1 ? 'disabled':''}}">Next</a>
                    <a href="{{route('slides.updateorder',[$slide,'action'=>'previous'])}}"
                       class="btn btn-light float-right {{$slide->order == 0 ? 'disabled':''}}">Previous</a>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center mb-5">
        <h1 class="m-0 mr-3">Projects</h1> <a href="{{route('projects.create')}}" class="btn btn-outline-primary">+</a>
    </div>
    <div class="row justify-content-center">
        <!-- Display user projects -->
        @foreach($projects as $project)
            <div class="card" style="width: 18rem;">
                @if (count($project->slides) > 1)
                    <img src="{{$project->slides[0]->image->url}}" class="card-img-bottom" alt="slide image">
                @endif
                <div class="card-body">
                    <h5 class="card-title">{{$project->name}}</h5>
                    <a href="{{ url('projects/'.$project->id.'/edit') }}" class="btn btn-primary">Open</a>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('js')
    <script>
        let slides = {!! json_encode($slides) !!}
    </script>
    <script src="{{ asset('js/preview.js') }}" defer></script>
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center mb-5">
            <a href="{{route('projects.edit',$project)}}" class="btn btn-outline-primary">Exit preview</a>
        </div>
        <div class="row justify-content-center mb-5">
            <h1 class="m-0 mr-3">Slide <span id="slide_nb"></span></h1>
        </div>
        <div id="canvas" class="text-center">
            @foreach($slides_orm as $slide)
                <img src="{{url($slide->image->url)}}" id="{{$slide->id}}" class="mySlides">
            @endforeach
        </div>



    </div>
@endsection