routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/slides/{slide}/updateorder','SlideController@updateOrder')->name('slides.updateorder');


Route::resource('projects','ProjectController');
Route::resource('projects.slides','SlideController')->shallow();
Route::resource('slides.animation','AnimationController');

app/Animation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Animation extends Model
{
    protected $fillable = ['name','param_model'];
}

app/Http/Controllers/AnimationController.php
<?php

namespace App\Http\Controllers;

use App\Animation;
use App\Slide;
use Illuminate\Http\Request;

class AnimationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $slide_id
     * @param $anim_id
     * @return void
     */
    public function edit($slide_id,$anim_id)
    {
        //Get slide ORM
        $slide = Slide::find($slide_id);
        $anim = Animation::find($anim_id);
        $array = array(
            'slide' => $slide,
            'animation' => $anim
        );

        //Return corresponding view for this animation
        switch($anim_id){
            case 1: return view('animations.edit.kenburns',$array);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $slide_id,$anim_id)
    {
        //Get validation json from database
        $anim = Animation::find($anim_id);
        $validation_json = json_decode($anim->param_model,true);

        $validatedData = $request->validate($validation_json);

        //Save new data to slide
        $slide = Slide::find($slide_id);
        $slide->anim_param = $validatedData;
        $slide->save();

        return redirect(route('slides.edit',[$slide]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/animations/edit/kenburns.blade.php
@extends('layouts.app')

@section('js')
    <script>
        let image = {!! json_encode($slide->image) !!};
        let anim_param = {!! json_encode($slide->anim_param) !!};
    </script>
    <script src="{{ asset('js/kenburns.js') }}" defer></script>
@endsection

@section('content')
    <div class="container">
        <!-- Effect preview row -->
        <div class="row">
            <div class="w-100 h-100" id="canvas"></div>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
    @endif
        <!-- Parameter row -->
        <div class="row">
            <form class="w-100" method="POST" action="{{route('slides.animation.update',[$slide,$slide->animation])}}">
                @csrf
                @method('PUT')

                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="startScale">Start scale</label>
                            <input type="text" id="startScale" name="startScale" class="form-control" placeholder="Start scale">
                            @error('startScale')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="endScale">End scale</label>
                            <input type="text" id="endScale" name="endScale" class="form-control" placeholder="End scale">
                            @error('endScale')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="startX">Start X position</label>
                            <input type="text" id="startX" name="startX" class="form-control" placeholder="Start X">
                            @error('startX')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="startY">Start Y position</label>
                            <input type="text" id="startY" name="startY" class="form-control" placeholder="Start Y">
                            @error('startY')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="endX">End X position</label>
                            <input type="text" id="endX" name="endX" class="form-control" placeholder="End X">
                            @error('endX')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="endY">End Y position</label>
                            <input type="text" id="endY" name="endY" class="form-control" placeholder="End Y">
                            @error('endY')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Save</button>
                <a href="{{route('slides.edit',$slide)}}" class="btn btn-danger">Cancel</a>
            </form>
        </div>
    </div>
@endsection