routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/slides/{slide}/updateorder','SlideController@updateOrder')->name('slides.updateorder');


Route::resource('projects','ProjectController');
Route::resource('projects.slides','SlideController')->shallow();
Route::resource('slides.animation','AnimationController');

app/Slide.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slide extends Model
{
    protected $fillable = ['duration','order','anim_param'];

    public function image(){
        return $this->belongsTo('App\Image');
    }

    public function animation(){
        return $this->belongsTo('App\Animation');
    }

    public function project(){
        return $this->belongsTo('App\Project');
    }
}

app/Http/Controllers/SlideController.php
<?php

namespace App\Http\Controllers;

use App\Animation;
use App\Image;
use App\Project;
use App\Slide;
use Illuminate\Http\Request;

class SlideController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($project_id)
    {
        //Get corresponding project
        $project = Project::find($project_id);
        //Get all project slides
        $slides = $project->slides;

        //TODO : return slides
        abort(405);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($project_id)
    {
        $project = Project::find($project_id);
        $animations = Animation::all();
        return view('slides.create', [
            'project' => $project,
            'animations' => $animations
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $id_project)
    {
        $validatedData = $request->validate([
            'slideImage' => 'required|image|mimes:jpeg,png,jpg',
            'slideDuration' => 'required',
            'animationSelect' => 'required'
        ]);

        $project = Project::find($id_project);
        $image     = new Image;
        $slide     = new Slide;

        if ($request->file('slideImage')) {
            $imagePath = $request->file('slideImage');
            $imageName = $imagePath->getClientOriginalName();

            $path = $request->file('slideImage')->storeAs('uploads', $imageName, 'public');

            //$image->name = $imageName;
            $image->url = '/storage/'.$path;
            $image->save();
            $slide->image()->associate($image);
        }
        $slide->duration = $validatedData['slideDuration'];

        //Animation
        if($validatedData['animationSelect'] != -1){
            $animation = Animation::find($validatedData['animationSelect']);
            $slide->animation()->associate($animation);
        }

        //Set slide order
        $slide->order = count($project->slides);

        //Save slide into project
        $project->slides()->save($slide);

        //Redirect to toute a modifier
        return redirect(route('projects.edit', $id_project));

    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //TODO : Check if the user is the owner of this slide
        $slide = Slide::find($id);
        $animations = Animation::all();

        //Return edit view
        return view('slides.edit', [
            'slide' => $slide,
            'animations' => $animations
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'slideImage' => 'image|mimes:jpeg,png,jpg',
            'slideDuration' => 'required',
            'animationSelect' => 'required'
        ]);

        $slide       = Slide::find($id);
        $image      = $slide->image;

        if ($request->file('slideImage')) {
            $imagePath = $request->file('slideImage');
            $imageName = $imagePath->getClientOriginalName();

            $path = $request->file('slideImage')->storeAs('uploads', $imageName, 'public');

            //$image->name = $imageName;
            $image->url = '/storage/'.$path;
            $image->save();
        }

        if($validatedData['animationSelect'] != -1){
            $anim = Animation::find($validatedData['animationSelect']);
            $slide->animation()->associate($anim);
        }else{
            $slide->animation_id = null;
        }

        $slide->duration = $validatedData['slideDuration'];

        $slide->save();

        $project = $slide->project;
        return redirect(route('projects.edit', $project));
    }

    public function updateOrder(Request $request, $id){
        $validateData = $request->validate([
            'action' => 'required',
        ]);

        $slide = Slide::find($id);
        $project = $slide->project;
        $slides = $project->slides()->orderBy('order','desc')->get();

        $prev_slide = $slides->where('order','<',$slide->order)->max('id');
        $next_slide = $slides->where('order','>',$slide->order)->min('id');

        if($validateData['action'] == 'next'){
            if($next_slide == null) abort(400);

            $temp = Slide::find($next_slide);
            $new_order = $temp->order;
            $temp->order = $slide->order;
            $temp->save();

            $slide->order = $new_order;
            $slide->save();
        }else if($validateData['action'] == 'previous'){
            if($prev_slide == null) abort(400);

            $temp = Slide::find($prev_slide);
            $new_order = $temp->order;
            $temp->order = $slide->order;
            $temp->save();

            $slide->order = $new_order;
            $slide->save();
        }
        return redirect(route('projects.edit',$project));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $slide = Slide::find($id);
        $project = $slide->project;
        $slides = $project->slides()->orderBy('order','desc')->get();

        //Re-order slides
        foreach($slides as $s){
            if($s->order > $slide->order){
                $new_order = $s->order;
                $new_order--;
                $s->order = $new_order;
                $s->save();
            }
        }

        $slide->delete();

        return redirect(route('projects.edit',$project));
    }
}

resources/views/slides/create.blade.php
@extends('layouts.app')

@section('js')
    <script>
        //Set event
        window.onload = function(){
            document.getElementById('slideImage').addEventListener("change",function(event){
                loadFile(event);
            });
            let loadFile = function(event) {
                let preview = document.getElementById('preview');
                let label = document.getElementById('slideImageLabel')
                //Load image into preview
                preview.src = URL.createObjectURL(event.target.files[0]);
                label.innerHTML = event.target.files[0].name;
                preview.onload = function() {
                    URL.revokeObjectURL(preview.src) // free memory
                }
            };
        }

    </script>
@endsection

@section('content')
    <div class="container">
        <h1 class="text-center">Create your new slide</h1>

        <form method="POST" action="{{ route('projects.slides.store',$project) }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <img src="" id="preview" alt="image upload preview" class="img-fluid mb-2">
                <div class="custom-file mb-3">
                    <label class="custom-file-label" for="slideImage" id="slideImageLabel">Choose image file</label>
                    <input type="file" accept="image/*" name="slideImage" id="slideImage"
                           class="custom-file-input @error('slideImage') is-invalid @enderror">
                    @error('slideImage')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="input-group mb-3">
                    <input type="text" id="slideDuration" name="slideDuration" class="form-control @error('slideDuration') is-invalid @enderror" placeholder="Enter slide duration (in seconds)" aria-describedby="basic-addon1">
                    <div class="input-group-append">
                        <span class="input-group-text" id="basic-addon1">s</span>
                    </div>
                    @error('slideDuration')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="animationSelect"><b>(optional)</b> Set an animation for this slide</label>
                    <select class="form-control @error('animationSelect') is-invalid @enderror" id="animationSelect" name="animationSelect">
                        @foreach($animations as $animation)
                            <option value="-1" selected>none</option>
                            <option value="{{$animation->id}}">{{ $animation->name }}</option>
                        @endforeach
                    </select>
                    <small id="animationSelectHelp" class="form-text text-muted">You can access the animation edit menu after the slide creation</small>
                    @error('animationSelect')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

            </div>

            <button type="submit" class="btn btn-success">Create</button>
            <a href="{{url()->previous()}}" class="btn btn-danger">Cancel</a>
        </form>
    </div>
@endsection

resources/views/slides/edit.blade.php
@extends('layouts.app')

@section('js')
    <script>
        window.onload = function(){
            //Set event
            document.getElementById('slideImage').addEventListener("change",function(event){
                loadFile(event);
            });
            let loadFile = function(event) {
                let preview = document.getElementById('preview');
                let label = document.getElementById('slideImageLabel')
                //Load image into preview
                preview.src = URL.createObjectURL(event.target.files[0]);
                label.innerHTML = event.target.files[0].name;
                preview.onload = function() {
                    URL.revokeObjectURL(preview.src) // free memory
                }
            };
        }
    </script>
@endsection

@section('css')

@endsection

@section('content')
    <div class="container">
        <h1 class="text-center">Edit this slide</h1>

        <form method="POST" action="{{ route('slides.update',$slide) }}" enctype="multipart/form-data">
            @csrf
            @method('PUT')

            <div class="form-group">
                <img src="{{($slide->image->url)}}" id="preview" alt="image upload preview" class="img-fluid mb-2">
                <div class="custom-file mb-3">
                    <label class="custom-file-label" for="slideImage" id="slideImageLabel">{{$slide->image->url}}</label>
                    <input type="file" accept="image/*" name="slideImage" id="slideImage"
                           class="custom-file-input @error('slideImage') is-invalid @enderror">
                    @error('slideImage')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="input-group mb-3">
                    <input type="text" id="slideDuration" name="slideDuration" value="{{$slide->duration}}"
                           class="form-control @error('slideDuration') is-invalid @enderror"
                           placeholder="Enter slide duration (in seconds)" aria-describedby="basic-addon1">
                    <div class="input-group-append">
                        <span class="input-group-text" id="basic-addon1">s</span>
                    </div>
                    @error('slideDuration')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <label for="animationSelect"><b>(optional)</b> Set an animation for this slide</label>
                <div class="form-row align-items-center">
                    <div class="col">

                        <select class="form-control @error('animationSelect') is-invalid @enderror" id="animationSelect"
                                name="animationSelect" autocomplete="off">
                            @if($slide->animation == null)
                                <option value="-1" selected="selected">none</option>
                                @foreach($animations as $animation)
                                    <option
                                        value="{{$animation->id}}">{{ $animation->name }}</option>
                                @endforeach
                            @else
                                <option value="-1">none</option>
                                @foreach($animations as $animation)
                                    <option
                                        value="{{$animation->id}}" {{ $animation->id == $slide->animation->id ? 'selected':'' }}>{{ $animation->name }}</option>
                                @endforeach
                            @endif

                        </select>
                    </div>
                    <div class="col">
                        @if($slide->animation == null)
                            <a href="" class="btn btn-primary disabled">Edit animation</a>
                        @else
                            <a href="{{route('slides.animation.edit',[$slide,$slide->animation])}}" class="btn btn-primary">Edit animation</a>
                        @endif
                    </div>

                    @error('animationSelect')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

            </div>

            <button type="submit" class="btn btn-success">Save</button>
            <a href="{{url('projects/'.$slide->project->id.'/edit')}}" class="btn btn-danger">Cancel</a>
            <form method="POST" action="{{route('slides.destroy',$slide)}}">
                @csrf
                @method('DELETE')
                <button class="btn btn-danger float-right">Delete this slide</button>
            </form>

        </form>
    </div>
@endsection